spring:
  application:
    name: loans
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:loansdb
    username: loans
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9005
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
info:
    app:
        version: 0.0.1
        description: Learning Project Microservices Loans Microservice